Arbolado/Proyecto_Arbolado/Proyecto_Arbolado/urls.py
"""Proyecto_Arbolado URL Configuration """

from django.contrib import admin
from django.urls import path, re_path, include
# Importamos los settings
from django.conf import settings
# Importamos los archivos estáticos
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.arbolado.urls')),
    re_path('', include('applications.solicitudes.urls')),
    # Ckeditor urls
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Arbolado/Proyecto_Arbolado/applications/arbolado/urls.py
from django.urls import path
from . import views

app_name = "arbolado_app"

urlpatterns = [
    
    path(
        'arbolado/register/section', 
        views.SectionCreateView.as_view(),
        name = 'arbolado_section',
    ), 

    path(
        'arbolado/register/tree', 
        views.TreeCreateView,
        name = 'register_tree',
    ), 

    path(
        'arbolado/delete/tree',
        views.TreeDeleteView,
        name = 'delete_tree',
    ),

    path(
        'arbolado/alcaldias/',
        views.TownListView.as_view(),
        name = 'arbolado_alcaldias',
    ),

    path(
        'arbolado/alcaldias/sections/<name>',
        views.ListSectionsByTown.as_view(),
        name = 'arbolado_sections'
    ),

    path(
        'arbolado/alcaldias/section/detail/<int:pk>',
        views.SectionDetailView.as_view(),
        name = 'arbolado_section_detail'
    ),
]

Arbolado/Proyecto_Arbolado/applications/arbolado/models.py
# Django modules
from django.db import models
# Local Managers
from .managers import SectionManager
# Third Party Apps
from ckeditor_uploader.fields import RichTextUploadingField

# Módelo Alcaldía
class Town(models.Model):
    
    name = models.CharField(
        'Town name',
         max_length = 30
    )

    image = models.ImageField(
        'Image', 
        upload_to ='Towns', 
    )

    def __str__(self):
        return self.name 

# Modelo Especie
class Species(models.Model):
    
    name = models.CharField(
        'Species name',
         max_length = 50
    )

    class Meta:
        verbose_name = 'Species'
        verbose_name_plural = 'Species'

    def __str__(self):
        return self.name 

# Modelo Ubicación
class Location(models.Model):
    
    name = models.CharField(
        'Location name',
         max_length = 50
    )

    class Meta:
        verbose_name = 'Location'
        verbose_name_plural = 'Locations'

    def __str__(self):
        return self.name 

# Modelo Árbol
class Tree(models.Model):

    STATUS_CHOICES = (
        ( '0', 'Muy Bueno' ),
        ( '1', 'Bueno' ),
        ( '2', 'Declinante Incipiente' ),
        ( '3', 'Declinante Severo' ),
        ( '4', 'Muerto' )
    )
    
    # Foreignkey from 'Species' model
    species = models.ForeignKey(
        Species, 
        on_delete = models.CASCADE
    )

    # django-ckeditor field 
    description = RichTextUploadingField()
    
    image = models.ImageField(
        'Image', 
        upload_to ='Trees', 
    )

    status = models.CharField(
        'Conservation Status', 
        max_length = 1, 
        choices = STATUS_CHOICES
    )

    amount = models.PositiveIntegerField('Amount') 
    
    class Meta:
        verbose_name = 'Tree'
        verbose_name_plural = 'Trees'

    def __str__(self):
        return str(self.id) + ': ' + self.species.name 

# Modelo Sección
class Section(models.Model):

    # Trees registered in the section  
    trees = models.ManyToManyField( Tree )

    # Location name
    location_name = models.CharField(
        'Location',
         max_length = 60
    )

    # Foreignkey from 'Location' model
    location_type = models.ForeignKey(
        Location, 
        on_delete = models.CASCADE
    )

    # Address provided by Google Maps
    address = models.TextField('Address')

    coords = models.CharField(
        'Coordinates',
         max_length = 200,
         blank = True
    )

    image = models.ImageField(
        'Image', 
        upload_to ='Sections', 
        null = True
    )

    # Foreignkey from 'Town' model
    town = models.ForeignKey(
        Town, 
        on_delete = models.CASCADE
    )

    # Linking the Manager with the model 
    objects = SectionManager()

    def __str__(self):
        return self.town.name + ': ' + self.location_name

Arbolado/Proyecto_Arbolado/applications/arbolado/forms.py
# Django Modules
from django import forms
# Django Models
from .models import Section, Species, Town, Tree

# Section Form
class SectionForm(forms.ModelForm):
    """Form definition for Section""" 

    town = forms.ModelChoiceField(
        required = True,
        queryset = Town.objects.all(),
        empty_label = "Selecciona una...",
    ) # ChoiceField bonded to Town model

    address = forms.CharField(
        required=True,
        widget = forms.Textarea(
            attrs={
                'placeholder': 'Seleciona la ubicación de la sección en el mapa...',
                'rows': '4',
                'cols': '50',
                'disabled': 'true', # Disable a field in the template ( HTML Document )
            }
        )
    )
    
    # The fields that are not specified in this section won´t be registered in the Database
    class Meta:
        model = Section
        fields = (
            'trees',
            'location_name',
            'location_type',
            'address',
            'coords',
            'image',
            'town'
        )

class TreeForm(forms.ModelForm):
    """Form definition for Tree"""
    
    species = forms.ModelChoiceField(
        required = True,
        queryset = Species.objects.all(),
        empty_label = "Selecciona una...",
    ) # ChoiceField bonded to Species model

    description = forms.CharField(
        required=True,
        widget = forms.Textarea(
            attrs={
                'placeholder': 'Tamaño, altura, características...',
                'rows': '4',
                'cols': '50',
            }
        )
    )

    amount = forms.IntegerField(
        required = True,
        min_value = 1,
        widget = forms.NumberInput(
            attrs={
                'value': '1'
            }
        )
    ) 

    class Meta:
        model = Tree
        # Or fields = ('__all__')
        fields = (
            'species',
            'description',
            'image',
            'status',
            'amount'       
        )

Arbolado/Proyecto_Arbolado/applications/arbolado/views.py
# Django Modules 
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    CreateView,
    DeleteView,
    ListView,
    DetailView,
)
# Django Models
from .models import Section, Tree, Town, Location
# Django Forms
from .forms import SectionForm, TreeForm

class SectionCreateView(CreateView):
    template_name = 'arbolado/register_section.html'
    model = Section
    form_class = SectionForm
    success_url = '.'
    
    def get_context_data(self, **kwargs):
        context = super(SectionCreateView, self).get_context_data(**kwargs)
        # Sending the TreeForm to the HTML template
        context["form_tree"] = TreeForm
        return context

    def form_invalid(self, form, **kwargs):
        context = self.get_context_data(**kwargs)
        print( f'Solicitud Enviada: {self.request.POST}')
        context['form'] = form
        print( f'Formulario inválido: { form.cleaned_data } ')
        return self.render_to_response( context )

    def form_valid(self, form):
        if self.request.is_ajax():
            data = dict()
            print( f'Solicitud Enviada: {self.request.POST}')
            print('---- AJAX REQUEST ----')
            section = form.save()
            data['id']     = section.id
            data['status'] = 'ok'
            return JsonResponse( data, status = 200 )
        else:
            return super(SectionCreateView, self).form_valid( form )
    
def TreeCreateView( request ):
    # Request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        data = {}
        # Get the form data, request.FILES for images, files and other kind of multimedia stuff
        form = TreeForm( request.POST, request.FILES )
        # Save the data and after fetch the object in an instance
        if form.is_valid():
            tree = form.save()
            data['id']          = tree.id
            data['species']     = tree.species.name
            data['description'] = tree.description
            data['status']      = tree.get_status_display()
            data['amount']      = tree.amount
            return JsonResponse(data, status = 200)
        else:
            # Some form errors occured
            return JsonResponse({ "error": form.errors}, status = 400)
    
    return JsonResponse({ "error": form.errors}, status = 400)


def TreeDeleteView( request ):
    # Request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        data = {}
        print(f'SOLICITUD ENVIADA PARA ELIMINAR EL ÁRBOL {request.POST}')
        # Getting the id form the POST Request
        id_tree = request.POST['id_tree']
        # Deleting the tree from the Database
        Tree.objects.filter( id = id_tree ).delete()
        # Sending the JSON Response to the Front-End
        data['status'] = 'Árbol Eliminado'
        return JsonResponse(data, status = 200)
    else:
        # Some form errors occured
        return JsonResponse({ "error": 'No Response'}, status = 400)
    
    return JsonResponse({ "error": 'No Response'}, status = 400)


class TownListView(ListView):
    template_name = 'arbolado/alcaldias.html'
    model = Town
    context_object_name = 'towns'
    ordering = 'name'
    

class ListSectionsByTown(ListView):
    template_name = 'arbolado/alcaldia_secciones.html'
    model = Section
    ordering = 'location_name'
    
    context_object_name = 'sections'
    def get_queryset(self):
        print(f'GET REQUEST: {self.request.GET}')
        # Retrieving the elements sended by GET Requests only 
        location_name = self.request.GET.get('kword', '')
        location_type = self.request.GET.get('location', '')
        print(f'KWARGS DICTIONARY: {self.kwargs}')
        # Retrieving the element from the URL taged with 'name' this is specified in the urls.py file
        # arbolado/alcaldias/sections/<name> -> <name> element that was sended in the URL
        town_name = self.kwargs['name']
        # Searching the Sections with the given parameters
        query_result = Section.objects.search_section( location_name, location_type, town_name)
        return query_result
    
    def get_context_data(self, **kwargs):
        context = super(ListSectionsByTown, self).get_context_data(**kwargs)
        context['locations'] = Location.objects.all()
        return context

class SectionDetailView(DetailView):
    template_name = 'arbolado/secion_detail.html'
    model = Section
    
    

    
    

Arbolado/Proyecto_Arbolado/templates/arbolado/alcaldia_secciones.html
{% extends "arbolado/base_arbolado.html" %}

{% load  static %}

{% block content %} 
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <!-- Foundation Block: 12 columns with margin between them -->
        <div class="grid-x grid-margin-x">
            
            <div class="cell large-8 large-offset-2 rectangle-green" style="margin-bottom: 30px;">
                <p> Consultas de Secciones de Arbolado </p>
            </div>

            <!-- Inicio Bloque Secciones -->
            <div class="cell large-8">
                <form class="input-group" method="GET"> {% csrf_token %}
                    <input class="text input-group-field" autocomplete="off" type="text" id="kword" name="kword" placeholder="Buscar Sección Arbolado ...">
                    <div class="input-group-button">
                      <input type="submit" class="button search-button-green" value="Buscar">
                    </div>
                </form>

                {% for section in sections  %}
                    <div class="callout success">
                        <p class="card-title"> {{ section.location_name }} </p>
                        <p class="card-text"> <span> Dirección: </span> {{ section.address }}  </p>
                        <p class="card-text"> <span> Tipo Ubicación: </span> {{ section.location_type.name }}  </p>
                        <p class="card-text"> <span> Total de Especies Árboles Registrados: </span> {{ section.trees.all.count }}  </p>
                        <div style="text-align: right;">
                            <a href="{% url 'arbolado_app:arbolado_section_detail' section.id %}" class="link-green"> Ver más... </a>
                        </div>
                    </div>
                {% empty %}
                <h3 class="sub-title"> No hay secciones registradas ... </h3>
                {% endfor %}
            </div>
            <div class="cell small-2 large-offset-1">
                <h4 class="subtitle"> Ubicación: </h4>
                <ul class="vertical menu">
                    {% for location in locations %}
                        <!-- This parameter is sending in the url by GET Method -->
                        <li> 
                            <a href="?location={{ location.name }}" class="link-green"> - {{ location.name }} </a> 
                        </li>    
                    {% endfor %}
                </ul>
            </div>
            <!-- Fin Bloque Secciones -->
        </div>
    </div>
{% endblock content %}

Arbolado/Proyecto_Arbolado/templates/arbolado/alcaldias.html
{% extends "arbolado/base_arbolado.html" %}

{% load  static %}

{% block content %} 
    {% include 'includes/header.html' %}
    <!-- Init Grid Container -->
    <div class="grid-container">
        <!-- Foundation Block: 12 columns with margin between them -->
        <div class="grid-x grid-margin-y grid-margin-x">
           <div class="cell rectangle-green">
             <p> Secciones de Arbolado por Alcaldía </p>
           </div>
           
            {% for town in towns  %}
            <div class="cell large-4 image-hover-wrapper">
              <a href="{% url 'arbolado_app:arbolado_sections' town.name %}"> <img src="{{ town.image.url }}">
                <span class="image-hover-wrapper-reveal">
                  <p> {{ town.name }} </p>
                </span>
              </a>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- End Grid Container -->
{% endblock content %}
    

Arbolado/Proyecto_Arbolado/templates/arbolado/base_arbolado.html
<!-- Heredamos todo lo que van a tener en común todos nuestros templates -->
{% extends "base.html" %}
<!-- Cargamos nuestros archivos estáticos que se encuentran en la carpeta 'statics' -->
{% load  static %}

{% block css %}
<!-- Estilos CSS para la aplicación Arbolado -->
    <link rel="stylesheet" href="{% static 'css/arbolado.css' %}">
{% endblock css %}
    
{% block js %}
<!-- Archivos JavaScript para la aplicación Arbolado -->
{% endblock js %}

Arbolado/Proyecto_Arbolado/templates/arbolado/register_section.html
{% extends "arbolado/base_arbolado.html" %}

{% load  static %}

{% block content %}

    {% include 'includes/header.html' %} 
    <!-- Init Grid Container -->
    <div class="grid-container ">
        <div class="grid-x grid-margin-x">
            <h3 class="cell title"> Registro de una Sección de Arbolado </h3>
            <!-- Inicio Bloque Ubicación -->
            <form id="formSection" method="POST" autocomplete="off" class="cell large-6"> {% csrf_token %}
                    <h4 class="cell subtitle"> Ubicación </h4>
                    
                    <div class="cell large-12">
                        <label class="text"> Nombre de la Ubicación:
                            {{ form.location_name }}
                        </label>
                    </div>

                    <div class="cell large-12">
                        <label class="text"> Tipo de Ubicación:
                            {{ form.location_type }}
                        </label>
                    </div>

                    <div class="cell large-12">
                        <label class="text"> Dirección:
                            {{ form.address }}
                        </label>
                    </div>

                    <div class="cell large-12">
                        <label class="text"> Alcaldía:
                            {{ form.town }}
                        </label>
                    </div>
            </form>
            <!-- Fin Bloque Ubicación -->

            <!-- Inicio Bloque Datos Árbol -->
                <form id="formTree" method="POST" autocomplete="off" class="cell large-6"> {% csrf_token %}
                        <h4 class="cell subtitle"> Agregar Árbol </h4>
                        
                        <div class="cell large-12">
                            <label class="text"> Especie:
                                {{ form_tree.species }}
                            </label>
                        </div>
    
                        <div class="cell large-12">
                            <label class="text"> Descripción:
                                {{ form_tree.description }}
                            </label>
                        </div>
    
                        <div class="cell large-12">
                            <label class="text"> Fotografía: </label>
                            {{ form_tree.image }}
                        </div>
    
                        <div class="cell large-12">
                            <label class="text"> Estado de Conservación: 
                                {{ form_tree.status }}
                            </label>
                            
                        </div>
                        <!-- Foundation Block: 12 columns -->
                        <div class="cell grid-x grid-margin-x">
                            <div class="cell large-6">
                                <label class="text"> Cantidad:
                                    {{ form_tree.amount }}
                                </label>
                            </div>
                            <div class="cell large-6" style="text-align: right;">
                                <br>
                                <img id="btnAddTree" height="40px" width="40px" style="cursor: pointer;" src="{% static 'img/add.png' %}">
                            </div>
                        </div>   
                </form>
            <!-- Fin Bloque Datos Árbol -->
        </div>

        <div class="cell">
            <table id="table-tree" style="margin-top: 20px;">
                <thead class="table-header-green">
                  <tr>
                    <th class="text-format"> Especie     </th>
                    <th class="text-format"> Descripción </th>
                    <th class="text-format"> Estado Conservación </th>
                    <th class="text-format"> Cantidad </th>
                    <th class="text-format"> Acción   </th>
                  </tr>
                </thead>
                <tbody id="tbodyTable" style="text-align: center;">
                </tbody>
              </table>
        </div>

        <div class="cell" style="text-align: right;">
            <button style="background-color: #81BDA4;" class="button" id="btnEnviar"> Enviar Solicitud </button>
        </div>

    </div>
    <!-- End Grid Container -->

   <!-- {% include "includes/footer.html" %} -->

{% endblock content %}
    

Arbolado/Proyecto_Arbolado/templates/arbolado/secion_detail.html
{% extends "arbolado/base_arbolado.html" %}

{% load  static %}

{% block content %} 
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <!-- Foundation Block: 12 columns with margin between them -->
        <div class="grid-x grid-margin-x">
            <div class="cell large-8 large-offset-2 rectangle-green" style="margin-bottom: 30px;">
                <p> {{ section.location_name }}  </p>
            </div>
            
            <!-- Inicio Bloque Contenido 6 columnas -->
            <div class="cell large-6 grid-margin-x">

                <div class="cell grid-x grid-margin-x">
                    <p class="cell large-2 font"> Dirección: </p>
                    <p class="cell large-10 fontxt"> {{ section.address }}</p>
                </div>
                
                <div class="cell grid-x grid-margin-x">
                    <p class="cell large-2 font"> Ubicación: </p>
                    <p class="cell large-10 fontxt"> {{ section.location_type.name }}</p>
                </div>
                
                <div class="cell grid-x grid-margin-x">
                    <p class="cell large-2 font"> Alcaldía: </p>
                    <p class="cell large-10 fontxt"> {{ section.town.name }}</p>
                </div>

            </div>
            <!-- Fin Bloque Contenido 6 columnas -->

            <!-- Inicio Bloque Imagen 6 columnas -->
            <div class="cell large-6">
                <div class="card">
                    <div class="card-section">
                        <img src="{% static 'img/logo.png' %}" alt="">
                    </div>
                </div>
            </div>
            <!-- Fin Bloque Imagen 6 columnas -->
            <h4 class="cell title"> Arbolado Registrado </h4>
            <!-- Inicio Bloque de Tabla de Árboles -->
            <div class="cell">
                <table id="table-tree">
                    <thead class="table-header-green">
                      <tr>
                        <th class="text-format"> Especie </th>
                        <th class="text-format"> Cantidad </th>
                        <th class="text-format"> Estado   </th>
                        <th class="text-format"> Acción   </th>
                      </tr>
                    </thead>
                    <tbody id="tbodyTable" style="text-align: center;">
                        {% for tree in section.trees.all %}
                        
                        <div class="reveal" id="modal_{{tree.id}}" data-reveal>
                            <p class="lead" style="text-align: center;"> {{ tree.species.name }} </p>
                            <p class="text-modal-format"> Arboles Registrados: {{ tree.amount }} </p>
                            <p class="text-modal-format"> Estado de Conservación: {{ tree.get_status_display }} </p>
                            <p class="text-modal-format"> Descripción: {{ tree.description|safe }} </p>
                            <p class="lead" style="text-align: center;"> Fotografía </p>
                            <img src="{{ tree.image.url }}" style="border: 8px solid #81BDA4;">
                            <button class="close-button" data-close aria-label="Close modal" type="button">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        <!-- Table Content -->
                        <tr>
                            <td class="text-format"> {{ tree.species.name }} </td>
                            <td class="text-format"> {{ tree.amount }} </td>
                            <td class="text-format"> {{ tree.get_status_display }} </td>
                            <td class="text-format"> 
                                <img src="{% static 'img/add.png' %}" data-open="modal_{{tree.id}}" height="25" width="25" style="cursor: pointer;">
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
            <!-- Fin Bloque de Tabla de Árboles -->
            
        </div>
    </div>
{% endblock content %}