Arbolado/Proyecto_Arbolado/Proyecto_Arbolado/urls.py
"""Proyecto_Arbolado URL Configuration """

from django.contrib import admin
from django.urls import path, re_path, include
# Importamos los settings
from django.conf import settings
# Importamos los archivos estáticos
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.arbolado.urls')),
    re_path('', include('applications.solicitudes.urls')),
    # Ckeditor urls
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Arbolado/Proyecto_Arbolado/applications/arbolado/urls.py
from django.urls import path
from . import views

app_name = "arbolado_app"

urlpatterns = [
    
    path(
        'arbolado/register/section', 
        views.SectionCreateView.as_view(),
        name = 'arbolado_section',
    ), 

    path(
        'arbolado/register/tree', 
        views.TreeCreateView,
        name = 'register_tree',
    ), 

    path(
        'arbolado/delete/tree',
        views.TreeDeleteView,
        name = 'delete_tree',
    ),

    path(
        'arbolado/alcaldias/',
        views.TownListView.as_view(),
        name = 'arbolado_alcaldias',
    ),

    path(
        'arbolado/alcaldias/sections/<name>',
        views.ListSectionsByTown.as_view(),
        name = 'arbolado_sections'
    ),

    path(
        'arbolado/alcaldias/section/detail/<int:pk>',
        views.SectionDetailView.as_view(),
        name = 'arbolado_section_detail'
    ),
]

Arbolado/Proyecto_Arbolado/applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path(
        # Al dejarlo en blanco indicamos que sea la página principal
        '', 
        views.HomePageView.as_view(),
        name = 'index',
    ), 
    
]

Arbolado/Proyecto_Arbolado/applications/solicitudes/urls.py
from django.urls import path

from . import views

app_name = "solicitudes_app"

urlpatterns = [
    
    path(
        'solicitudes/section/register', 
        views.SolicitudeRegisterView.as_view(),
        name='section_register',
    ), 

    path(
        'solicitudes/trees/report', 
        views.SolicitudeReportView.as_view(),
        name='trees_report',
    ),
    
    # Consultas
    path(
        'solicitudes/search/section/report', 
        views.SolicitudesSeccionArboladoView.as_view(),
        name='search_section_report',
    ),

    path(
        'solicitudes/search/issues/report', 
        views.SolicitudesReportesView.as_view(),
        name='search_issues_report',
    ),

]

Arbolado/Proyecto_Arbolado/templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7"> Contacto:</h3>
        <p class="cell large-8">  Email: {{ contact_email }} </p>
        <p class="cell large-8"> Teléfono: {{ contact_phone   }}  </p>
        <p class="cell large-8"> {{ contact_message }}  </p>
    </div>
</div>

Arbolado/Proyecto_Arbolado/templates/includes/header.html
{% load static %}
<header>
  <div class="multilevel-offcanvas off-canvas position-right" id="offCanvasRight" data-off-canvas>
    <ul class="vertical menu" data-accordion-menu>
      <li><a href="#"> ALCALDÍAS </a>
        <ul class="menu vertical nested">
          <li><a href="{% url 'arbolado_app:arbolado_alcaldias' %}"> Consultar Secciones Arbolado </a></li>
         </ul>
      </li>
      <li><a href="#"> ENVIAR UNA SOLICITUD </a>
        <ul class="menu vertical nested">
          <li><a href="{% url 'solicitudes_app:section_register' %}"> Solicitud Registro Arbolado  </a></li>
          <li><a href="{% url 'solicitudes_app:trees_report' %}"> Solicitud Registro Indicente </a></li>
         </ul>
      </li>
      <li><a href="#"> SEGUIMIENTO DE SOLICITUDES </a>
        <ul class="menu vertical nested">
          <li><a href="{% url 'solicitudes_app:search_section_report' %}"> Registro Sección Arbolado </a></li>
          <li><a href="{% url 'solicitudes_app:search_issues_report' %}"> Registro de Incidentes   </a></li>
         </ul>
      </li>
     </ul>
    <ul class="vertical menu">
       <li><a href="#"> Iniciar Sesión </a></li>
       <li><a href="#">FAQ</a></li> 
       <li><a href="#">Terms & Conditions</a></li>
    </ul>
    
  </div>
  
  <div class="off-canvas-content" data-off-canvas-content>
    <div class="nav-bar">
        <div class="nav-bar-left">
          <a class="nav-bar-logo" href="{% url 'home_app:index' %}"> <img class="logo" src="{% static 'img/logo.png' %}""> </a>
        </div>
        <div class="nav-bar-right">
          <button class="offcanvas-trigger" type="button" data-open="offCanvasRight">
            <span class="offcanvas-trigger-text hide-for-small-only"> Menu </span>
            <div class="hamburger">
              <span class="line"></span>
              <span class="line"></span>
              <span class="line"></span>
            </div>
          </button>
      </div>
    </div>
  </div>

</header>  
  